# tasks file
---
- name: install | git | dependencies
  ansible.builtin.apt:
    name: "{{ keepalived_dependencies_git }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - keepalived-install-git-dependencies

- name: install | git | create (checkout) directory
  ansible.builtin.file:
    path: "{{ keepalived_checkout_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - keepalived-install-git-checkout
    - keepalived-install-git-checkout-directory

- name: install | git | checkout repository
  ansible.builtin.git:
    repo: "{{ keepalived_git_repo }}"
    dest: "{{ keepalived_checkout_path }}"
    version: "{{ keepalived_version }}"
    force: true
  register: _git_checkout
  tags:
    - keepalived-install-git-checkout-repository

- name: install | git | regenerate the build files
  ansible.builtin.shell: >
    aclocal && autoheader && automake --add-missing && autoreconf
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when:
    - _git_checkout is changed
    - keepalived_version is version('v1.2.24', '>=')
    - keepalived_version is version('v2.1.0', '<')
  tags:
    - keepalived-install-git-build
    - keepalived-install-git-build-regenerate-build-files

- name: install | git | regenerate the build files
  ansible.builtin.shell: >
    ./build_setup
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when:
    - _git_checkout is changed
    - keepalived_version is version('v2.1.0', '>=')
  tags:
    - keepalived-install-git-build
    - keepalived-install-git-build-regenerate-build-files

- name: install | git | build
  ansible.builtin.shell: >
    ./configure {{ keepalived_configure_options | join(' ') }} && make -j{{ ansible_processor_cores + 1 }}
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when: _git_checkout is changed
  tags:
    - keepalived-install-git-build
    - keepalived-install-git-build-configure-make

- name: install | git | remove (distro version)
  ansible.builtin.apt:
    name: keepalived
    state: absent
    purge: true
  tags:
    - keepalived-install-git-remove
    - keepalived-install-git-remove-distro

- name: install | git | install
  ansible.builtin.shell: >
    make install
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when: _git_checkout is changed
  notify: restart keepalived
  tags:
    - keepalived-install-git-install

- name: install | git | add script user
  ansible.builtin.user:
    name: keepalived_script
    comment: 'keepalived script'
    home: /nonexistent
    shell: /bin/false
    system: yes
  when: keepalived_create_keepalived_script_user | bool
  tags:
    - keepalived-install-git-script
    - keepalived-install-git-script-user

- name: install | git | cleanup build
  ansible.builtin.shell: >
    git reset --hard && git clean -d -x -f
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when: _git_checkout is changed
  tags:
    - keepalived-install-git-cleanup
    - keepalived-install-git-cleanup-build
