# tasks file for keepalived
---
- name: install dependencies
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: keepalived_dependencies
  when: ansible_os_family == 'RedHat'
  tags:
    - configuration
    - keepalived
    - keepalived-install
    - keepalived-install-redhat

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    force: yes
    update_cache: true
    cache_valid_time: 3600
  with_items: keepalived_dependencies
  when: ansible_os_family == 'Debian'
  tags:
    - configuration
    - keepalived
    - keepalived-install
    - keepalived-install-debian

- name: update configuration file
  template:
    src: etc/keepalived/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0640
  notify: restart keepalived
  tags:
    - configuration
    - keepalived
    - keepalived-configuration

- name: allow binding non-local IP
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "{{ keepalived_ip_nonlocal_bind }}"
    reload: true
    state: present
  when: keepalived_ip_nonlocal_bind != false
  tags:
    - configuration
    - keepalived
    - keepalived-ip-nonlocal-bind

- name: start and enable service
  service:
    name: keepalived
    state: started
    enabled: true
    # Pattern is needed to fix failure in Ubuntu 10.04 and idempotency in 12.04 and 14.04
    pattern: /usr/sbin/keepalived
  tags:
    - configuration
    - keepalived
    - keepalived-start-enable-service
