# tasks file
---
- name: install additional
  apt:
    name: "{{ keepalived_install }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - keepalived
    - keepalived-install
    - keepalived-install-additional

- name: install | git
  include: git.yml
  when: keepalived_install_method == 'git'
  tags:
    - configuration
    - keepalived
    - keepalived-install
    - keepalived-install-git

- name: install | native
  include: native.yml
  when: keepalived_install_method == 'native'
  tags:
    - configuration
    - keepalived
    - keepalived-install
    - keepalived-install-native

- block:

    - name: allow binding non-local IPv4
      sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: "{{ keepalived_ip_nonlocal_bind | string }}"
        reload: true
        state: present
      when: keepalived_ip_nonlocal_bind | bool

    - name: check if IPv6 is enabled
      slurp:
        src: /sys/module/ipv6/parameters/disable
      register: _ipv6_disabled

    - name: set ipv6_enabled fact
      set_fact:
        is_ipv6_enabled: "{{ not _ipv6_disabled.failed and '0' in (_ipv6_disabled.content | b64decode) }}"

    - name: allow binding non-local IPv6
      sysctl:
        name: net.ipv6.ip_nonlocal_bind
        value: "{{ keepalived_ip_nonlocal_bind | string }}"
        reload: true
        state: present
      when:
        - keepalived_ip_nonlocal_bind | bool
        - is_ipv6_enabled

  tags:
    - configuration
    - keepalived
    - keepalived-ip-nonlocal-bind

- name: create (checkout) directory
  file:
    path: "{{ keepalived_checkout_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - keepalived
    - keepalived-checkout
    - keepalived-checkout-directory

- name: checkout repository
  git:
    repo: "{{ keepalived_git_repo }}"
    dest: "{{ keepalived_checkout_path }}"
    version: "{{ keepalived_version }}"
    force: true
  register: _git_checkout
  tags:
    - configuration
    - keepalived
    - keepalived-checkout
    - keepalived-checkout-repository

- name: regenerate the build files
  shell: >
    aclocal && autoheader && automake --add-missing && autoreconf
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when:
    - _git_checkout is changed
    - keepalived_version is version('v1.2.24', '>=')
    - keepalived_version is version('v2.1.0', '<')
  tags:
    - configuration
    - keepalived
    - keepalived-build
    - keepalived-build-regenerate-build-files

- name: regenerate the build files
  shell: >
    ./build_setup
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when:
    - _git_checkout is changed
    - keepalived_version is version('v2.1.0', '>=')
  tags:
    - configuration
    - keepalived
    - keepalived-build
    - keepalived-build-regenerate-build-files

- name: build
  shell: >
    ./configure {{ keepalived_configure_options | join(' ') }} && make -j{{ ansible_processor_cores + 1 }}
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when: _git_checkout is changed
  tags:
    - configuration
    - keepalived
    - keepalived-build
    - keepalived-build-configure-make

- name: remove (distro version)
  apt:
    name: keepalived
    state: absent
    purge: true
  tags:
    - configuration
    - keepalived
    - keepalived-remove
    - keepalived-remove-distro

- name: install
  shell: >
    make install
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when: _git_checkout is changed
  notify: restart keepalived
  tags:
    - configuration
    - keepalived
    - keepalived-install

- name: add script user
  user:
    name: keepalived_script
    comment: 'keepalived script'
    home: /nonexistent
    shell: /bin/false
    system: yes
  when: keepalived_create_keepalived_script_user | bool
  tags:
    - configuration
    - keepalived
    - keepalived-script
    - keepalived-script-user

- name: cleanup build
  shell: >
    git reset --hard && git clean -d -x -f
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when: _git_checkout is changed
  tags:
    - configuration
    - keepalived
    - keepalived-cleanup
    - keepalived-cleanup-build

=======
>>>>>>> origin/master
- name: stat directories
  stat:
    path: "{{ item }}/"
  register: _stat_directories
  with_items:
    - "{{ keepalived_configuration_file | dirname }}"
  tags:
    - configuration
    - keepalived
    - keepalived-configure-directories
    - keepalived-configure-directories-stat

- name: create directories
  file:
    path: "{{ item.item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{ _stat_directories.results }}"
  when: not item.stat.exists
  tags:
    - configuration
    - keepalived
    - keepalived-configure-directories
    - keepalived-configure-directories-create

- name: update configuration file
  template:
    src: "{{ keepalived_configuration_file.lstrip('/') }}.j2"
    dest: "{{ keepalived_configuration_file }}"
    owner: root
    group: root
    mode: 0640
  notify: restart keepalived
  tags:
    - configuration
    - keepalived
    - keepalived-configuration

- name: copy script files
  copy:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    owner: "{{ item.value.owner | default('root') }}"
    group: "{{ item.value.group | default('root') }}"
    mode: "{{ item.value.mode | default('0750') }}"
  with_dict: "{{ keepalived_vrrp_script_map }}"
  notify: restart keepalived
  tags:
    - configuration
    - keepalived
    - keepalived-scripts

- include: service-upstart.yml
  when: ansible_service_mgr != 'systemd'
  tags:
    - configuration
    - keepalived
    - keepalived-service
    - keepalived-service-upstart

- include: service-systemd.yml
  when: ansible_service_mgr == 'systemd'
  tags:
    - configuration
    - keepalived
    - keepalived-service
    - keepalived-service-systemd

- name: start and enable service
  service:
    name: keepalived
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - keepalived
    - keepalived-start-enable-service
