# tasks file
---
- name: service | systemd | update script
  ansible.builtin.template:
    src: "{{ keepalived_etc_systemd_file.lstrip('/') }}.j2"
    dest: "{{ keepalived_etc_systemd_file }}"
    owner: root
    group: root
    mode: 0644
  register: _update_systemd_script
  notify: restart keepalived
  tags:
    - keepalived-service-systemd-update

- name: service | systemd | reload
  ansible.builtin.systemd:
    daemon_reload: true
  when: _update_systemd_script is changed
  tags:
    - keepalived-service-systemd-reload
